# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/OPSIDIAN-nbdev',
                'doc_host': 'https://panukorn17.github.io',
                'git_url': 'https://github.com/panukorn17/OPSIDIAN-nbdev',
                'lib_path': 'OPSIDIAN_nbdev'},
  'syms': {'OPSIDIAN_nbdev.core': {'OPSIDIAN_nbdev.core.foo': ('core.html#foo', 'OPSIDIAN_nbdev/core.py')}}}
