# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_cfd_utils.ipynb.

# %% auto 0
__all__ = ['create_analysis_container', 'setup_fluid_properties']

# %% ../nbs/03_cfd_utils.ipynb 5
import FreeCAD as App


# %% ../nbs/03_cfd_utils.ipynb 6
import CfdOF
def create_analysis_container():
    """
    Function to create the analysis container on freeCAD

    Parameters:
    shape (Part.Shape): The object to be analysed
    """
    # create a cfd analysis group object
    analysis = CfdOF.CfdAnalysis.makeCfdAnalysis('CfdAnalysis')
    CfdOF.CfdTools.setActiveAnalysis(analysis)
    analysis.addObject(CfdOF.Solve.CfdPhysicsSelection.makeCfdPhysicsSelection())
    analysis.addObject(CfdOF.Solve.CfdFluidMaterial.makeCfdFluidMaterial('FluidProperties'))
    analysis.addObject(CfdOF.Solve.CfdInitialiseFlowField.makeCfdInitialFlowField())
    analysis.addObject(CfdOF.Solve.CfdSolverFoam.makeCfdSolverFoam())

# %% ../nbs/03_cfd_utils.ipynb 8
def setup_fluid_properties(name='Water', type='Isothermal', density='998 kg/m^3', dynamicViscosity='1.003e-3 kg/m/s'):
    """
    Function to set up the fluid properties for CfdOF
    """
    print("Setting up fluid proberties")
    if name == 'Water':
        desc = 'Standard distilled water properties at 20 Degrees Celsius and 1 atm'
        App.ActiveDocument.FluidProperties.Label = 'Water'
    else:
        desc = ''
        App.ActiveDocument.FluidProperties.Label = 'Fluid'
    App.ActiveDocument.FluidProperties.Material = {'CardName': name + type,
                                       'AuthorAndLicence': '',
                                       'Name': name,
                                       'Type': type,
                                       'Description': desc,
                                       'Density': density,
                                       'DynamicViscosity': dynamicViscosity}
