# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['freecad_path', 'cfdof_path']

# %% ../nbs/00_core.ipynb 2
import sys
sys.path.append("..")
freecad_path = r"C:\Program Files\FreeCAD 0.21\bin"
cfdof_path = r'C:\Users\ASUS\AppData\Roaming\FreeCAD\Mod\CfdOF'
if freecad_path not in sys.path:    
    sys.path.append(freecad_path)
if cfdof_path not in sys.path:    
    sys.path.append(cfdof_path)

# %% ../nbs/00_core.ipynb 3
import FreeCAD as App
